### ISSUE TITLE
Signed up for the free extra month but status says 61 days left

### ISSUE THREAD

**Issue by will-stone** [microdotblog/issues#10]
I signed up for the 2 months + 1 extra month but http://micro.blog/account/domains shows 61 days left. I would have thought it should say 90ish days.

**Comment by manton** [comment]
This is a display bug. Behind the scenes it really should be a full 3 months credit with Stripe. I'm going to take some time and go through accounts to correct the date.

**Comment by will-stone** [comment]
Ok, cool. Thanks.

**Comment by will-stone** [comment]
I am no longer a paid customer, and the 61 days are long gone. I can only presume this was fixed. Closing.
