### ISSUE TITLE
Add theme without stylesheets

### ISSUE THREAD

**Issue by niksurff** [microdotblog/issues#106]
At the moment I'm able to override a theme with a custom style sheet which is lovely.

I'd love to have a bare bones theme with semantic markup and probably reasonably named classes on core elements but no stylesheet loaded other than `custom.css` so I can take full control over the design without making the user download unused bytes. :octocat:

**Comment by manton** [comment]
@niksurff Thanks for the feedback! I think that's a great idea. (I'm also working toward letting you upload or edit more of the theme, which should help too for customizing it.)

**Comment by niksurff** [comment]
I believe this issue is obsolete now that @manton implemented custom themes for us. Excited to play around with this feature, thanks a bunch. ❤️
