### ISSUE TITLE
Feature Request: Reputation / Vote system (Upvoting / Downvoting)

### ISSUE THREAD

**Issue by rlue** [microdotblog/issues#108]
To me, upvoting/downvoting posts is one of the most important features on many forum / community sites, and one of the big draws of centralized services over independent blogging. Didn't see it anywhere else in the issue tracker, so I'm putting in the request here.

**Comment by manton** [comment]
@rlue Thanks for the suggestion!

**Comment by RickCogley** [comment]
Sorry to butt in: in my opinion, I think the fact that there _is_ no up/downvote system, that makes Micro.blog special, and more focused on the conversation, where dissent can of course occur, rather than reducing it to a click. Jmo.

**Comment by manton** [comment]
I'm going to close this for now since I don't think up/downvoting fits well with the current design and goals of Micro.blog. We don't have an algorithmic timeline so there wouldn't really be anything to do with the data that is collected from votes. Thanks again for the feedback.
