### ISSUE TITLE
Github mirroring: not working

### ISSUE THREAD

**Issue by RickCogley** [microdotblog/issues#116]
Hi - I'm rickcogley on micro.blog, and Github mirroring to https://github.com/RickCogley/rickcogley.github.io is not working for me at all. Here's what I tried: 

* created a blank repo, just putting a readme during the setup process. 
* setup the GH token selecting "repo" permission
* entered the token and tried variations of the path in the setup box on `https://micro.blog/account/mapping/xxxx`:

~~~~~
   RickCogley/rickcogley.github.io
   rickcogley/rickcogley.github.io
   https://github.com/RickCogley/rickcogley.github.io
~~~~~

I understand the mirroring happens a couple times a day on a schedule, but a couple days have passed without any new commits in the repo. 

Wonder if someone could kindly look into it and advise what I should do or correct to fix it?

**Comment by RickCogley** [comment]
Still not working... what gives?

**Comment by wragge** [comment]
Ditto.

**Comment by jemostrom** [comment]
It hasn't worked for a while (I think 10 Dec) and the reason is that there has been some problems with how micro.blog work with GitHub (if I've understood Manton correctly). He has written that he is working on a better way for exporting a blog and, as I understand it, a better way to interact with Github.

**Comment by splorp** [comment]
Has anyone heard if progress is being made on this?

**Comment by jemostrom** [comment]
Marton has implemented an export feature to replace it

**Comment by splorp** [comment]
> Marton has implemented an export feature to replace it

Oh, I must have missed that when it first rolled out.

Thanks!

**Comment by pyrmont** [comment]
I don't believe the export feature is meant to replace it (or has there been an announcement?). [The last time](https://micro.blog/manton/2400618) @manton talked about it with me, he said the plan was still to bring it back.

**Comment by issimonwoods** [comment]
There is now an [archive to GitHub feature](https://www.manton.org/2020/08/04/bringing-back-github.html), although it’s not exactly the same as the previous mirroring option.

**Comment by pyrmont** [comment]
@manton Looks like this issue can now be closed.

**Comment by manton** [comment]
Yep, we've changed how this works but it should be working now. Closing.
