### ISSUE TITLE
All Sent Replies Page

### ISSUE THREAD

**Issue by joshcsullivan** [microdotblog/issues#122]
Hi, I would like to request that a page that shows you all of the replies you have sent on Micro.blog is added.

Thanks!

**Comment by ghost** [comment]
The 'Show More' should at least be present on this page and any other similar page (Discover, etc).

**Comment by issimonwoods** [comment]
We now have a Replies page for our blogs and a Replies manager for editing. Do either of those fulfil this request?

**Comment by manton** [comment]
Yes, I think this can be closed now. Thanks.
