### ISSUE TITLE
Show More button has a gap on iPhone X

### ISSUE THREAD

**Issue by ghost** [microdotblog/issues#123]
Reported by Jason Burk [in this post](https://micro.burk.io/2018/12/27/on-iphone-x.html). Caught by Jonathan and Manton [in the attached thread](https://micro.blog/Burk/1588219).

![micro-blog_show-more_iphone-x](https://user-images.githubusercontent.com/45672577/50545174-cb318980-0c02-11e9-95be-6b82848d4922.jpg)

**Comment by manton** [comment]
I think this is looking better now. Thanks!
