### ISSUE TITLE
CSS and page edits needs to be quicker

### ISSUE THREAD

**Issue by ghost** [microdotblog/issues#127]
Hoping Manton's comment on #106 hints at improvements to performance as well as options, and whilst delays are understandable this particular part of the site is now out of sync with the timeline which has become _much_ faster over the past year.

**Comment by manton** [comment]
Yep, this is going to become much faster. I'll have a longer post later on the upcoming changes for themes. Thanks!

**Comment by issimonwoods** [comment]
Huh. Didn’t realised this had been re-opened. Maybe more updates are on the way 😇

**Comment by manton** [comment]
I'm always looking for ways to make it faster but some of the biggest changes have been rolled out, so probably no need to keep this open. Thanks.
