### ISSUE TITLE
My first post published twice

### ISSUE THREAD

**Issue by will-stone** [microdotblog/issues#13]
I can't seem to reproduce this now and I've deleted the posts, but when I first signed-up for Micro.blog and posted using `https://micro.blog/posting`, the post showed twice (duplicated) on `https://micro.blog/stone`. Maybe it was because it was my very first post?

**Comment by paulrobertlloyd** [comment]
I too experienced the same (although have not experienced this since). I think there were some caching issues during the first few days, so fixing those may have fixed this issue – hopefully!

**Comment by orionp** [comment]
My first post also showed twice, and upon deleting one copy via timeline... the other still shows in the timeline, yet not in my Posts listing when editing via the Accounts page. Ghost post endures!

**Comment by will-stone** [comment]
No other complaints about this. Assuming it's fixed.
