### ISSUE TITLE
Internal Server Error when trying to update User Description on Web

### ISSUE THREAD

**Issue by jpersson** [microdotblog/issues#131]
The server returns a 500 (Internal server error) when trying to submit the about-me form on the Account page. 

```
URL: https://micro.blog/account/update
Status: 500 Internal Server Error
Source: Network
Address: 104.200.22.215:443
```

**Comment by jpersson** [comment]
Seems to be an issue when using emoji in the description. I guess it should be handled nicer :-)

**Comment by manton** [comment]
Thanks for the bug report. Looks like you're right, it doesn't allow emoji currently. I'll get this fixed.

**Comment by sardisson** [comment]
@manton You [fixed this recently](https://www.manton.org/2019/07/30/you-can-now.html), correct?

**Comment by manton** [comment]
Yes, this was fixed. Thanks!
