### ISSUE TITLE
Please support syntax colouring

### ISSUE THREAD

**Issue by ronaldoussoren** [microdotblog/issues#132]
The HTML generated from markdown source code blocks seems to be ready for the use of prism.js, but that library is not used on HTML that shows up on a micro.blog site.

I'd like to be able to include snippets of source code in posts, such as in [this post](https://blog.ronaldoussoren.net/2018/12/07/fun-with-async.html).

**Comment by ronaldoussoren** [comment]
Custom themes made I easy to add this myself, just clone the theme I use and add the CSS and JS I need for syntax colouring on my blog.

**Comment by niksurff** [comment]
@ronaldoussoren there's also a simpler method. Micro.blog recently switched to Hugo as its static site generator. Have a look at [the docs](https://gohugo.io/content-management/syntax-highlighting/) for details on syntax highlighting.

@manton maybe Hugo shortcodes (and other features) could be documented on [help.micro.blog](https://help.micro.blog)?

I cobbled together a blog post to document and test the feature for myself: [Testing Syntax Highlighting On Micro.blog Powered Websites](https://blog.lazylife.ninja/2019/02/05/testing-syntax-highlighting.html).

:octocat:

**Comment by ronaldoussoren** [comment]
Adding support for prism.js was easy as well, see  [this post](https://blog.ronaldoussoren.net/2018/12/07/fun-with-async.html) for the result.

**Comment by pamoroso** [comment]
@niksurff were you able to make syntax highlighting work with code fences wrapped in triple backticks as you described [here](https://blog.lazylife.ninja/2019/02/05/testing-syntax-highlighting.html)?

**Comment by niksurff** [comment]
@pamoroso Indeed. Thanks for reminding me. I just updated my `config.json`.

Also it didn't work for me before. I believe [the fix described in this update by @manton](https://www.manton.org/2019/04/28/deployed-some-server.html) could have resolved the issue.

Just add a custom theme and place the following snipped into your `config.json`:

```json
{
  "pygmentsCodeFences": true
}
```

If you go back to my post you linked above the second code block is now highlighted correctly. I updated the post accordingly.

:octocat:

**Comment by pamoroso** [comment]
@niksurff Thanks. I guess if I want to use an existing theme I can just create a custom one based on it and set the Pygments option in `config.json`, right? BTW there's a typo in the update to your post: Micro.blow -> Micro.blog

**Comment by niksurff** [comment]
@pamoroso Yes, that's what I did. Thanks, I'll fix it.

**Comment by pamoroso** [comment]
@niksurff Is the code block with syntaxt highlighting supposed to be shown in the post editor's preview? If so I'm doing something wrong with the custom theme as you can see in the screenshot.

I created a new theme by cloning the Primrose one from Micro.blog's GitHub repo, added a `config.json` template, entered the Pygments option in the new template, and set the custom theme in my blog.

![screenshot-micro blog-2019 05 06-21-09-05](https://user-images.githubusercontent.com/10342479/57248897-dcbcef00-7043-11e9-840d-58c781e9e07a.png)

**Comment by niksurff** [comment]
@pamoroso no, this doesn't apply to the preview as it doesn't use your theme. You'll be able to see it on the public post page. It should work the way you described it.

**Comment by pamoroso** [comment]
Thanks, I'll try.

**Comment by pamoroso** [comment]
[It works](https://blog.paoloamoroso.com/2019/05/07/testing-syntax-highlighting.html), thanks again.

**Comment by pamoroso** [comment]
Never mind, only syntax highlighting works but the code block is formatted with a proportional font, not a monospaced one. @manton any insight?

**Comment by niksurff** [comment]
@pamoroso add this snipped of CSS to your themes' CSS or  [`custom.css`](https://help.micro.blog/2017/custom-css/)

```css
code {
    font-family: monospace;
}
```

**Comment by pamoroso** [comment]
@niksurff this did the trick, thanks a lot. I updated [my test post](https://blog.paoloamoroso.com/2019/05/07/testing-syntax-highlighting.html) and took the occasion to add your code snippet, which this time appears in all its monospaced, syntax-highlighted glory :-)

**Comment by niksurff** [comment]
@pamoroso glad you got it working. This stuff can be confusing.

@manton not to keep you away from more important tasks but might I suggest adding a help page for this kind of thing.

:octocat: ❤️

**Comment by manton** [comment]
Thanks everyone for working through this! Good point @niksurff, it would be nice to cover more of this in the help.
