### ISSUE TITLE
Include profile URL in macOS client

### ISSUE THREAD

**Issue by gerwitz** [microdotblog/issues#142]
Simple feature request: I want a (clickable) listing of a user's profile URL when viewing their profile on the macOS client.

Today, I have to manually derive their /user URL and view their web profile, which is silly.

**Comment by ghost** [comment]
Is this so you can link to the profile in some way, i.e. sharing it with other people?

**Comment by gerwitz** [comment]
No, I only want to visit their personal homepage. And see parity with the iOS and web clients.

God help me if instead of a clickable URL we had a share button that pulls up a menu with “copy link” in it. ;-)

**Comment by ghost** [comment]
Ohhh I misunderstood. Do you mean that any links on their profile should be clickable?

**Comment by gerwitz** [comment]
Ah, I guess I’m asking for two things. I lost my own thread, there!

Of course the “web site” value of the user’s profile should be present and clickable across all clients:
![iOS profile view](https://user-images.githubusercontent.com/73157/58154420-d6e52180-7c71-11e9-97bb-c71dc4678692.jpeg)

But I also want a link to their user profile URL so I can properly link to them when mentioning them from outside the Micro.blog tools.

I.e. I can use `@simonwoods` if I want to mention you when replying or posting to a hosted microblog, but posting to my self-hosted site I need to make an explicit link like `[@simonwoods](https://micro.blog/simonwoods)` because, well, how is any renderer to know I didn’t mean `https://twitter.com/simonwoods`?

I’d suggest this be exposed by making the @username title clickable (and context-clickable) as a link.

**Comment by manton** [comment]
I agree this is needed in the Mac app. The UI problem is that on the Mac, if you have multiple accounts set up, clicking on your profile name shows a popup menu to select a new account to use. So we'd need to modify that or have a separate menu item somewhere to quickly jump to the profile screen.

**Comment by gerwitz** [comment]
In the meantime, I'd be happy to just have it appear in the "more" menu for user profiles.

Just now, @vincent posted about Gluon, and I wanted to see how to get ahold of it. So I click on his avatar, and end up on this screen that really should lead me to http://micro.blog/vincent but just refuses to:
<img width="652" alt="image" src="https://user-images.githubusercontent.com/73157/65252986-28a39880-dafa-11e9-8049-e4bb1e7c8302.png">

**Comment by gerwitz** [comment]
I see that the in-app profile now includes the homepage link. This is a great start.

**Comment by manton** [comment]
I've added the site URL to the next Mac version. Thanks!
