### ISSUE TITLE
ssl certificate issue on micro.blog

### ISSUE THREAD

**Issue by kule** [microdotblog/issues#151]
Just to let you know you've got an ssl issue on the main site at the moment:

https://www.ssllabs.com/ssltest/analyze.html?d=micro.blog&s=104.200.22.215

https://www.ssllabs.com/ssltest/analyze.html?d=micro.blog&s=2600%3A3c00%3A1%3A0%3A0%3A0%3A68c8%3A16d7

Edit just to clarify; it's showing this in Mac Firefox 68 (Chrome & Safari are not showing as having a problem):

https://www.dropbox.com/s/tosveh2k7jdc54w/Screenshot%202019-07-29%2021.41.11.png?dl=0

**Comment by manton** [comment]
This was resolved recently. Thank you!
