### ISSUE TITLE
Include summary from Atom or JSON feed?

### ISSUE THREAD

**Issue by chriskrycho** [microdotblog/issues#157]
I'm publishing a valid JSON Feed (and will hopefully 🤞 be open-sourcing a plugin for [11ty](https://11ty.io) in the next month or so) and using its `summary` field, but that data is not being used in any way by micro.blog—I originally expected it would be included in the syndicated content in some way.

Is this intended behavior, just not a priority, or other? Thanks!

**Comment by manton** [comment]
This is intended behavior. Currently Micro.blog ignores `summary` for longer posts, instead just linking the title back to your blog. The thinking was that we don't really want the timeline full of summaries… Most of the posts in Micro.blog should be short posts or links to longer blog posts. One work-around for now would be to create a special JSON Feed for Micro.blog that includes the summary inside `content_html`.
