### ISSUE TITLE
Options for indiebookclub links

### ISSUE THREAD

**Issue by toddgrotenhuis** [microdotblog/issues#158]
Currently, indiebookclub links are a search on Amazon. Suggest one or more of the following changes:

* Have the link search on Indiebound, Openlibrary, or Alibris instead
* Allow users to choose the URL/search service to use
* Add the option for users to include their affiliate ID for the service that is linked

**Comment by ghost** [comment]
Does this only happen on the Micro.blog timeline/in Micro.blog hosted sites, or does it also happen on non-Micro.blog sites?

**Comment by toddgrotenhuis** [comment]
I'm on a hosted account. It appears to make a "micro.blog/books/" link that forwards to a Amazon search.

See an example here: e.g. https://blog.grotenhuis.info/2019/12/06/finished-reading-knife.html

**Comment by manton** [comment]
Good idea. I didn't expect that we'd stick with Amazon forever, just that it made a good default to start with. A setting on the blog itself makes sense to me.

As more people link to the same books, we could also point the URLs to a page that shows other blog posts about that book, with extra links for places to buy the book.

**Comment by manton** [comment]
I've changed the book links to add a simple preview page with the book cover and a link to Amazon and Bookshop.org. I think there's more we could do with this page later. Thanks!

**Comment by manton** [comment]
The book covers use https://openlibrary.org, and not all book covers are available. In the future we could pull covers and other book metadata from more sources.
