### ISSUE TITLE
No IndieAuth usable rel-me's for hosted option

### ISSUE THREAD

**Issue by chrisaldrich** [microdotblog/issues#17]
For those using the paid hosted domains, there doesn't seem to be a pathway by which rel="me" appears on either the main site URL (https://example.micro.blog) or the user page (https://micro.blog/example) to allow users to use IndieAuth to log into (webmention) applications like Quill, et al.

After putting in  a site in to the "Web Site" field on http://micro.blog/account and saving, I see the site appear on https://micro.blog/example, but it doesn't include a rel="me" link.
The only rel="me" link that appears on the user's site at https://example.micro.blog is one pointing to https://micro.blog/example, but that doesn't seem do one any good for IndieAuth.

It doesn't seem to be theme dependent, but I've tried it on both the Default and Hyde themes. (Not being able to flush the cache quickly kept me from testing them all, but I'm guessing they're relatively standardized aside from CSS.)

Ideally users with hosted domains should be given several web site fields (on the account settings page) in which they can put URLs into their profile: perhaps one for any related site they've got and then fields for any of the following IndieAuth capable authorization providers: Twitter, GitHub, Flickr, an SMS capable phone number, or an email address. These don't all need to be displayed in the UI, but should at least appear in the header (as links) on one or both of their pages so that they can be used for IndieAuth.

Examples for my presence as reference:
https://c.micro.blog
https://micro.blog.c

Thanks @manton!

**Comment by manton** [comment]
@chrisaldrich Thanks Chris. There actually is a setting to add `rel="me"` for Twitter and GitHub currently, but it's buried and so easy to miss. It's under Account -> Edit Apps. I realize this is not obvious, but I thought it should go there since it was about security.

I'd like to add more control over this so that it's not just limited to Twitter and GitHub. Let me know what you think.

**Comment by chrisaldrich** [comment]
<a href="https://github.com/microdotblog/issues/issues/17" class="u-in-reply-to"></a>Perhaps putting these fields and the phone number onto the main account page would be better UI? It will also bring forward the statement about IndieAuth (I like the description by the way), which will help to make other posting interfaces and applications more apparent--particularly in the early Beta days when they're so limited.  

Additionally adding a field for Instagram (wrapped with rel-me) will also let users potentially use https://ownyourgram.com/

Similarly a swarm/foursquare field for aaronpk's ownyourswarm would be useful, though he may have to do some tweaking to get it to work with micro.blog as it's relatively new.

Other than that I think I mentioned most of the other commonly used IndieAuth data pieces above.

**Comment by paulrobertlloyd** [comment]
Just been looking at this myself. I have a `link` (and an `a`) on my website pointing to <https://micro.blog/paulrobertlloyd> using `rel="me"`. However the (verified) URL that I’m including on my profile (<https://paulrobertlloyd.com>), does not include `rel="me"`. Maybe this was deemed unnecessary as Micro.blog doesn’t provide RelMeAuth, but I don’t believe that’s a pre-requisite for providing this attribute.

**Comment by manton** [comment]
Now that Micro.blog is a full IndieAuth provider I think these issues go away. Feel free to re-open if you see any problems. Thanks!

**Comment by paulrobertlloyd** [comment]
I’ve moved [my comment](
https://github.com/microdotblog/issues/issues/17#issuecomment-363250497) to a new issue: #102, limiting this issue to adding `rel="me"` to the URL on profile pages.
