### ISSUE TITLE
iOS app: An unsolicited redesign

### ISSUE THREAD

**Issue by paulrobertlloyd** [microdotblog/issues#171]
The [move to San Francisco](https://www.manton.org/2020/03/30/microblog-for-ios.html) had me thinking about the general design direction of the iOS app.

There’s certainly a line to be drawn between an iOS app being true to the platform and having its own personality. However, the Micro.blog currently falls somewhere between the two, and often finds itself existing in an uncanny valley - it looks almost native in places, but uses custom controls in others. However, on occasion it will lean too heavily on defaults, such as the blue tint for links and default blue hints for the in app browser.

With this in mind, I spent a few hours reviewing the app, and while not making any significant UX changes, tweaked things to feel less uncanny, while also aiming to be true to the Micro.blog brand. I found that a lot could be achieved by using a warmer hue for background colours, and picking iOS’s orange tint for links and controls.

Details of specific changes follow.

### Home screen

<img src="https://user-images.githubusercontent.com/813383/77954308-5bf38b00-72c6-11ea-84f9-93af20b5b359.png" width="375" alt="Home screen">

* Standard navigation bar (bolder title)
* Updated icon for new post
* Warmer hue for background behind user menu
* Menu items with separators that align with label text

### Profile screen and timeline

<img src="https://user-images.githubusercontent.com/813383/77954321-61e96c00-72c6-11ea-85ed-610dd368101a.png" width="375" alt="Profile screen">

* Standard navigation bar (bolder title)
* Show ‘Back’ label
* Warmer hue for background behind user profile
* Orange tint for links/actions in user profile
* Chevron for following item

I also updated the time stamps in the timeline. Is the reason these are not currently human readable because it’s difficult to localise them?

### In-app browser

<img src="https://user-images.githubusercontent.com/813383/77954315-5f871200-72c6-11ea-87e4-69b0de0caadb.png" width="375" alt="In-app browser">

* Use orange tint for controls

### Settings

The part of the app that most clearly charts its own path is the settings screen. I started looking at this but soon realised that redesigning this screen could be a project in and of itself – and one with many rabbit holes one could fall down! So, what I show here has many flaws, but hopefully gives you some idea of a general direction.

<img src="https://user-images.githubusercontent.com/813383/78064179-41361a80-7389-11ea-91dd-66ff76c0dc12.png" width="375" alt="Settings">

* Use modal display for this screen
* With #84 in mind, I started thinking about ways in which you could allow editing the settings for a WordPress or compatible blog. I soon realised that to accurately address this would take much effort, and missed the broader point of this exercise.
* Make link sharing format a switch, defaulting to Markdown
* Move links to help and sign out to this screen, and also add links to the news site and this GitHub issues site to report a bug
* Move the version information to the very bottom of the screen

#### …and updated home screen

The above changes would necessitate removing the equivalent menu items from the home screen, and placing a link to the settings screen in the top right:

<img src="https://user-images.githubusercontent.com/813383/77957535-8ac03000-72cb-11ea-95d1-b9561982d0bc.png" width="375" alt="Home (Alternative)">

I hope you don’t mind this unsolicited redesign, and I hope it provides some ideas/inspiration.

**Comment by patdryburgh** [comment]
This looks awesome, @paulrobertlloyd. The only change I would suggest would be to move the checkmark in the settings screen from the left to the right and line the text for the Publishing rows. But, without seeing it, I can imagine that moving it to the right conflicts with the chevron that would be beneath it. Everything else looks great to me :)

**Comment by paulrobertlloyd** [comment]
@patdryburgh Thanks! Reason for the checkmark being on the left was that I imagined that, if you had a WordPress site configured, you would see the info glyph as a hint that you could change its settings. Something like this, perhaps:

<img src="https://user-images.githubusercontent.com/813383/78063920-dab0fc80-7388-11ea-93bf-a62a6b99f040.png" width="375" alt="Setting screen, with WordPress configured">

Again, that’s just a quick thought, would need to think about all the different states etc.

**Comment by patdryburgh** [comment]
@paulrobertlloyd Aha! That makes a lot more sense :) While there may be another solution to this, I think this works well. Great job!

**Comment by paulrobertlloyd** [comment]
Closing this issue. [A new version of the iOS app is being designed](https://www.manton.org/2022/09/13/early-beta-of.html) which departs from the previous navigation method, and is more heavily branded, which is nice. It also has a design that is more consistent across iOS and Android platforms, which makes the above pretty much redundant 🙂
