### ISSUE TITLE
Twitter syndication truncating too aggressively.

### ISSUE THREAD

**Issue by gerwitz** [microdotblog/issues#172]
#55 seems to be a problem for me. Two recent examples:

- https://twitter.com/gerwitz/status/1246446450185306114
- https://twitter.com/gerwitz/status/1245279156734251009

**Comment by manton** [comment]
I think this is working correctly. In the first example, Micro.blog takes your link and appends the URL at the end for the tweet. It's about 275 characters without the URL, so adding the link takes it over 280 characters, forcing Micro.blog to truncate it before sending it to Twitter.

**Comment by manton** [comment]
Related, though, I've been considering adding a kind of Twitter-aware character counter or preview in the Micro.blog apps that can help explain what will happen.

**Comment by gerwitz** [comment]
Indeed…I understood the syndication behavior, but naively thought the editor’s character counter was already “Twitter aware”. (This makes more sense when you consider that I still engage people mostly on Twitter, but write many tweets as Micro.blog posts.)

Sorry for the distraction!
