### ISSUE TITLE
authentication issue

### ISSUE THREAD

**Issue by drsdayton** [microdotblog/issues#174]
I registered for an account today...

dstansfield@madriverpartners.com, with a user name @drsdayton

I can now log onto @drsdayton.micro.blog

but it doesn't recognize or correlate my email address. I want this email address and this username, but seem to be blocked at this point. Can you help sort out this account?

Thx,

Doug Stansfield

**Comment by manton** [comment]
Hi @drsdayton. I saw your email first so I followed up there earlier today. I'm going to delete this GitHub issue so your email address isn't shared publicly.
