### ISSUE TITLE
Rough time to mirror feeds?

### ISSUE THREAD

**Issue by chriskrycho** [microdotblog/issues#175]
I have cross-posting set up for my site, and I'm curious (and can't find any documentation about this): how long does Micro.blog take to mirror items from feeds (I publish both Atom and JSON feed) to the site? I haven't figured out any specific pattern, but it often takes over an hour. [This post](https://v5.chriskrycho.com/notes/1037/), for example, went up over an hour ago and there's no corresponding update to micro.blog yet.

**Comment by manton** [comment]
There are a few things that control how often it checks feeds. It tries to check them every 3 minutes, but if the server is overloaded or if you haven't used Micro.blog lately, it will wait longer.

If you'd like it to update more quickly, there's also an option to "ping" Micro.blog to tell it your feed has new posts in it. It's documented at the bottom of [this help page](https://help.micro.blog/2017/api-feeds/).

**Comment by chriskrycho** [comment]
Thanks! Is there any public info about the server load that I could check in the future? Regardless, much obliged!
