### ISSUE TITLE
Instagram auth failure in Sunlit

### ISSUE THREAD

**Issue by shawnyeager** [microdotblog/issues#178]
I just attempted to authorize my Instagram account from Sunlit for iOS, and was presented with the following error.

![image](https://user-images.githubusercontent.com/980297/87238846-8f69a980-c3cd-11ea-9b4c-4c9c041e28c9.jpeg)

I've force-quit the app and cleared the app cache, but see the same error. 

If relevant, I am using 2FA on my Instagram account.

**Comment by manton** [comment]
Thanks @shawnyeager, I haven't seen that before, but it sounds like something may have changed in the Instagram API. @cheesemaker, any ideas?

**Comment by cheesemaker** [comment]
Unfortunately, Instagram discontinued the API that we had been using on June 29th of this year. Also unfortunately, the replacement API is only available for users with Business/Professional accounts (aka not everyone). This is very much in line with what Facebook did with the Facebook Graph API so I'm not surprised. I don't think there's anything we can do to fix this. I'm very curious why I didn't get deprecation notifications from Instagram warning us of it. Perhaps they went into my spam bucket.

**Comment by manton** [comment]
Bummer. @shawnyeager, we are working on a brand new version of Sunlit. I'll be posting a sneak peek about it tomorrow, actually. If there's an opportunity for better integration with Instagram in the future, we can take another look at it.

**Comment by shawnyeager** [comment]
No worries. I'm mostly interested in moving off Instagram, rather then cross-posting. Cheers.

**Comment by manton** [comment]
If you're using macOS, another good option for migrating away from Instagram is to use the Micro.blog for macOS app to import your Instagram archive. https://help.micro.blog/2018/instagram-import/
