### ISSUE TITLE
macOS-client has a broken post-window in dark mode

### ISSUE THREAD

**Issue by nielsk** [microdotblog/issues#179]
When macOS 10.15 is set to dark mode then the post-window of the micro.blog-window is broken since buttons are white-ish and the text is white-ish as well. Screenshot is attached.
Micro.blog-client 1.9.3
macOS 10.15.5
 
![Screenshot 2020-07-16 at 05 49 54](https://user-images.githubusercontent.com/111362/87624683-9a536f80-c728-11ea-8b8c-aa4e0b10287c.png)

**Comment by manton** [comment]
As a work-around for now, the problem should go away if you restart the app. I think it only happens if dark mode changes while the app is running.

**Comment by nielsk** [comment]
Yes, that works as a workaround. Interestingly the other way around (start it in dark mode, start app, switch to light mode) the problem does not appear

**Comment by paulrobertlloyd** [comment]
Still an issue as of Micro.blog 2.0 (and goes away when you restart the app):

<img width="647" alt="Screenshot 2020-10-04 at 12 27 30" src="https://user-images.githubusercontent.com/813383/95014163-031dfa00-063d-11eb-84eb-9486ca1a2e67.png">

**Comment by manton** [comment]
Fixed for 2.0.2. Thanks.
