### ISSUE TITLE
iOS app: Allow more room to write an accessibility description

### ISSUE THREAD

**Issue by paulrobertlloyd** [microdotblog/issues#181]
<img src="https://user-images.githubusercontent.com/813383/91670676-85377200-eb17-11ea-9350-2e53420d03d8.jpg" alt="Screenshot of Micro.blog for iOS accessibility description dialog" width="320">

While an accessibility description shouldn’t be too long, to be effective it probably requires more characters than that currently able to be displayed in this dialog. Editing this text is made more difficult given iOS’s current text selection methods (infuriating would be an understatement!).

If this dialog displayed two lines of text, the usability of this important feature would be 100% better.

**Comment by issimonwoods** [comment]
I thought I saw this issues spoken about elsewhere but I can’t find it.

Either way this field remains the size shown in the screenshot.

**Comment by paulrobertlloyd** [comment]
Fixed in 3.0 🎉
