### ISSUE TITLE
macOS app: Can ‘Show Tab Bar’ on new post window 

### ISSUE THREAD

**Issue by paulrobertlloyd** [microdotblog/issues#182]
The menu option for `View` → `Show Tab Bar` is enabled for the new post window, but this window does not support tabs.

<img width="647" alt="Screenshot 2020-10-04 at 11 55 18" src="https://user-images.githubusercontent.com/813383/95013801-986bbf00-063a-11eb-8358-b87dcdc4cc53.png">

**Comment by manton** [comment]
Fixed for 2.0.2.
