### ISSUE TITLE
macOS app: No means of browsing all available discover categories

### ISSUE THREAD

**Issue by paulrobertlloyd** [microdotblog/issues#185]
Currently there is no way to view all discover tagemoji categories in the macOS app (the categories shown are random and change on page refresh).

<img width="739" alt="Screenshot 2020-10-04 at 12 00 13" src="https://user-images.githubusercontent.com/813383/95013991-d1f0fa00-063b-11eb-858d-ca22e6aa1d53.png">

**Comment by manton** [comment]
I'd like to make this match the iOS UI, with a popup of more choices.

**Comment by manton** [comment]
This has been added in version 2.1, released today.
