### ISSUE TITLE
Security

### ISSUE THREAD

**Issue by will-stone** [microdotblog/issues#19]
I know I logged this with you via email but thought it good to track here too. Pages should really default to `https` as Stripe doesn't like `http`:
![image](https://cloud.githubusercontent.com/assets/654103/25520318/68bdcf48-2bf3-11e7-85e2-b67b3496034e.png)
And it should help prevent cookie stealing / session hijacking to access accounts; a la Firesheep: https://codebutler.github.io/firesheep/

**Comment by heyvito** [comment]
Almost opened a new issue about this, but I think it's okay to chime in on this one. I noticed that even when browsing using HTTPs, some resources, like Gravatar images, are still transferred using HTTP. 🤔

**Comment by manton** [comment]
Thank you. I'll get this fixed and try to get everything redirecting to HTTPS soon. I'll do the payment pages first.

**Comment by paulrobertlloyd** [comment]
[Observatory by Mozilla](https://observatory.mozilla.org/) is a fantastic tool for validating a site’s security, and finding out how/what to change to strengthen it. At the time of writing, [micro.blog is scoring a D](https://observatory.mozilla.org/analyze.html?host=micro.blog) ☹️

**Comment by klundberg** [comment]
https://www.ssllabs.com/ssltest/ is another great scoring site for testing https implementations. I don't know how much it overlaps with mozilla's though.

I'd also advocate for HSTS (ideally for everything, but at a minimum on sensitive pages like account/payment/etc) so that users can't be transparently downgraded to insecure HTTP.

**Comment by manton** [comment]
Thanks for the links, @paulrobertlloyd and @klundberg. Definitely room for improvement here.

**Comment by will-stone** [comment]
Looks like pages are now in HTTPS. Closing.
