### ISSUE TITLE
Unable to add multiple external blogs in iOS client

### ISSUE THREAD

**Issue by lildude** [microdotblog/issues#199]
I'm trying to setup the iOS micro.blog client to connect to multiple external blogs but it appears this is no longer possible. Regardless of the number of accounts I sign into on the client, the first account is the only one that can be configured with an external blog and switching accounts always uses the same destination blog.

I'm pretty sure a different external URL could be added/selected by tapping the name in the bar below the text area but this doesn't respond to tapping.

I'm using version 2.0 from the app store. I've also completely removed micro.blog and Sunlit and reinstalled just micro.blog and the problem persists.

As an aside, I've also tried having my server respond with a `destinations` prop as per @manton's example at https://gist.github.com/manton/52e0015f87fcf50c687a0c64e392fc37 but this doesn't appear to work either.

**Comment by paulrobertlloyd** [comment]
@manton I think this issue can now be closed, as this is fixed in 3.0.
