### ISSUE TITLE
Unable to share photos from iOS share sheet

### ISSUE THREAD

**Issue by jjeaton** [microdotblog/issues#203]
I am unable to share photos with the micro.blog iOS when trying to add them through the share sheet from the photos app. I either get no response from tapping the micro.blog icon, or it attempts to switch (zooms out slightly) to the micro.blog app, and then returns to the share sheet. 

Is anyone else experiencing this or is this a known issue?

I'm on an iPhone 12 Pro latest version of iOS (14.3)

**Comment by manton** [comment]
I think this has been fixed now. Thanks!
