### ISSUE TITLE
Add scope selection to “Mirroring to GitHub” help page

### ISSUE THREAD

**Issue by splorp** [microdotblog/issues#21]
The [Mirroring to GitHub](http://help.micro.blog/2016/mirroring-to-github/) help page should mention that the `repo` scope needs to be selected when creating (or updating) a Personal Access Token before automatic pushing to GitHub will work.

![screenshot 2017-04-28 13 51 06](https://cloud.githubusercontent.com/assets/29835/25545011/38d401cc-2c1a-11e7-871b-dfe2b028b64a.png)

**Comment by manton** [comment]
Thanks! I've added a note about the "repo" scope to the documentation.

**Comment by splorp** [comment]
Thanks, Manton!
