### ISSUE TITLE
(iPad) Hover menu broken in conversations

### ISSUE THREAD

**Issue by issimonwoods** [microdotblog/issues#218]
Specifically conversations in which the first post contains more than one image.

Example:

<img width="1194" alt="MB bug_hover menu broken in convo" src="https://user-images.githubusercontent.com/81525353/121805989-b667d580-cc45-11eb-870b-2f0efe23f245.png">

If there was only a single image I think the menu would hover to the left.

**Comment by manton** [comment]
Fixed for the next version.
