### ISSUE TITLE
Custom theme CSS not mirrored to repo, empty commits created

### ISSUE THREAD

**Issue by splorp** [microdotblog/issues#22]
I added some custom CSS to my [splorp.micro.blog](http://splorp.micro.blog/) (running the default theme). I also have GitHub mirroring configured. When the CSS is updated, the changes are pushed to my site and a deployment is triggered for the GitHub repo.

However, the custom CSS does not get mirrored to GitHub (see first screenshot), even though sixteen separate commits are created (see second screenshot). Each of the commit details indicates that nothing was actually accomplished during the commit (see third screenshot).

![screenshot 2017-04-28 14 35 19](https://cloud.githubusercontent.com/assets/29835/25546547/c88de32c-2c20-11e7-8db7-2fac3fe90e7c.png)

![screenshot 2017-04-28 14 35 38](https://cloud.githubusercontent.com/assets/29835/25546548/c894a61c-2c20-11e7-9a89-718d0dbbf496.png)

![screenshot 2017-04-28 14 43 54](https://cloud.githubusercontent.com/assets/29835/25546675/56800b2e-2c21-11e7-87ee-5ee7c8a9af15.png)

**Comment by manton** [comment]
@splorp We've rolled out a few improvements to custom CSS support this morning. Depending on the theme, the CSS may not have been used or been overridden. If you still a problem, please let me know.

**Comment by manton** [comment]
I believe the issue of empty commits has now been fixed. Please let me know if you still see any issues.

**Comment by splorp** [comment]
Thanks @manton … things are looking much better now!
