### ISSUE TITLE
(iPad) Stray clickable area in the sidebar

### ISSUE THREAD

**Issue by issimonwoods** [microdotblog/issues#220]
You can click between _Discover_ and _Posts_ to reveal a grey bar that is just… there?

<img width="1194" alt="mb_odd-grey-bar-left-column-clickable" src="https://user-images.githubusercontent.com/81525353/121806328-4b1f0300-cc47-11eb-9fb3-04acb41d964d.png">

**Comment by manton** [comment]
I've fixed this for the next version.
