### ISSUE TITLE
Error posting a photo from the iOS app

### ISSUE THREAD

**Issue by benhager** [microdotblog/issues#23]
I have a site hosted by Micro.blog and a custom domain. When I try and post a photo from the iOS app I get this error:

![img_2777](https://cloud.githubusercontent.com/assets/2280717/25551237/047fc45c-2c50-11e7-9793-4094a4c42faf.PNG)

**Comment by dougbeal** [comment]
Worked just now on 1.0.1 

---
layout: post
date: 2017-04-29 18:58
---
[https://github.com/microdotblog/issues/issues/23](https://github.com/microdotblog/issues/issues/23) Bugs all the way down. Testing image upload with 1.0.1

<img src="http://dougbeal.micro.blog/uploads/2017/0ef4a5732a.jpg" width="600" height="600" style="height: auto" />

**Comment by jthingelstad** [comment]
I’m seeing this same problem. I also have a custom domain set. micro.thingelstad.com.

**Comment by jthingelstad** [comment]
Still doesn't work for me. Error is immediate. Worked fine up until Saturday mid-morning. Hasn't worked since.

**Comment by jthingelstad** [comment]
This is now resolved for me with today's build. @benhager can you confirm as well and we can close this issue?

**Comment by benhager** [comment]
@thingles yes, this is working for me after the update yesterday! I've tried it a few times now.
