### ISSUE TITLE
Micro bloggers add extra embeds when they reply to people in Mastodon

### ISSUE THREAD

**Issue by Ciantic** [microdotblog/issues#238]
When microbloggers reply to posts and tag people it adds extra embed link, see e.g. this:

(First login to Mastodon.social)

1. https://mastodon.social/@mcg@braintube.com/106609228936244656
2. https://mastodon.social/@brentsimmons@micro.inessential.com/109394743591213101

These extra embeds appear only when Micro Blogger tags people on other servers, if they tag people on same server they won't appear.

Normally when Mastodon users tag people on any server it won't add any embeds.

Notice these two embeds:

## 1. 
Notice Matthew is using Micro Blogging platform, when he tags someone it also adds embed:
<img src="https://user-images.githubusercontent.com/64731/203873175-eb14dc79-bf8b-411b-91c1-15031d3c2cae.png" width=500 />

## 2.
Brent uses Micro Blogging platform and when he tags someone it also adds embed.

Bert who uses Mastodon to reply it won't add embeds.

<img src="https://user-images.githubusercontent.com/64731/203873207-53e57757-8f17-4319-a7cd-c14f537727dc.png" width=500 />

**Comment by manton** [comment]
Thanks!

**Comment by manton** [comment]
I think I have this fixed for future replies.

**Comment by manton** [comment]
These were my test replies to try out the fix: https://mastodon.online/@manton/109405151531981377
