### ISSUE TITLE
Mobile UI suggestion: Chat bubble  or menu option to create post from home screen

### ISSUE THREAD

**Issue by chrisaldrich** [microdotblog/issues#24]
The Timeline, Mentions, and Favorites all have a "chat" icon in the upper right to allow one to create a status update. Why not also include this on the main homescreen (or a "Create Post" button just above Timeline) so there's one less step to posting? It also makes it easier for new users to figure out how to post.

**Comment by manton** [comment]
Thanks for the suggestion. This will be in the next build.
