### ISSUE TITLE
Bug(?): Deleted Categories showing in Archive page

### ISSUE THREAD

**Issue by leefeagin** [microdotblog/issues#243]
I deleted most of my (imported) categories (from WP), wanting to start over and utilize the Filters feature. Yet, when I load my Archive page, I still see them all listed at the top.

<img width="593" alt="image" src="https://github.com/microdotblog/issues/assets/13337458/f10911e3-fc16-4680-9275-efce77c47601">

<img width="749" alt="image" src="https://github.com/microdotblog/issues/assets/13337458/ad5733b6-a5ab-44a9-9634-6d04184e6163">

**Comment by manton** [comment]
Sorry about that. This will very likely fix itself, but it sometimes takes a minute (or longer) for the Archive page to be updated. If it still looks wrong to you, go into the Account → View logs page and click the "Rebuild" button, which will re-publish all pages on your blog.

**Comment by leefeagin** [comment]
Yeah, I forgot to mention the timeline in my original post. I let it sit there for about 24 hours before I opened the issue. The “Rebuild” options did work like a champ. Thanks for that!

I’ll leave it open if you need to keep it for research. If you’d like to close it, please feel free. Thanks!

**Comment by manton** [comment]
I updated Micro.blog for another fix for this. I think it should be working reliably now. Thanks!
