### ISSUE TITLE
webfinger url requires second @

### ISSUE THREAD

**Issue by jernst** [microdotblog/issues#245]
Given `@manton@micro.blog`, I would expect the Webfinger URL to be
`https://micro.blog/.well-known/webfinger?resource=acct%3amanton@micro.blog`, but that returns 404 and "User not found".

Instead, `https://micro.blog/.well-known/webfinger?resource=acct%3a@manton@micro.blog` (with the leading `@`) works but I don't think that is how Webfinger is supposed to work with the `acct:` scheme.

Also I don't think Webfinger clients do this -- e.g. typing `@manton@micro.blog` into Mastodon does not bring up anything.

**Comment by manton** [comment]
Thanks for the report. The 404 is actually correct because that's not my handle… It's `@manton@manton.org`. 🙂 However, that is weird about the extra `@`… That's definitely a bug because it's also including an invalid URL in the response. I'll get that fixed.

**Comment by manton** [comment]
This is fixed.
