### ISSUE TITLE
Content negotiation fails when Accept request header includes multiple types

### ISSUE THREAD

**Issue by snarfed** [microdotblog/issues#246]
Hi all! Apologies in advance, conneg is the worst. 😭

I noticed that AP `Follow`s from micro.blog to Bridgy Fed were failing, and I think I narrowed it down to micro.blog's server side content negotiation being a bit too naive.

When I fetch eg https://juhaliikala.com/activitypub/juha with a simple `Accept: application/activity+json`, micro.blog correctly returns AS2 JSON (after redirects). However, Bridgy Fed uses a more complicated `Accept: application/activity+json; q=0.9, application/ld+json;profile="https://www.w3.org/ns/activitystreams"; q=0.8, text/html; charset=utf-8; q=0.7`, which means it prefers AS2 JSON but will also accept HTML. When I fetch https://juhaliikala.com/activitypub/juha with that header, micro.blog returns HTML.

Is micro.blog maybe doing a simple == or prefix check for `application/activity+json` or `application/ld+json`? If so, any chance I could convince you all to upgrade to a more sophisticated handling that supports BF's `Accept`?

Sorry again, this truly is the worst. https://datatracker.ietf.org/doc/html/rfc7231#section-5.3 . Ugh.

**Comment by manton** [comment]
Thanks! I'm finally getting around to fixing this. Micro.blog's implementation was naive, although slightly different… I defaulted to JSON _unless_ the accepts contained `text/html`, so that a simple `curl` would return JSON to help debugging.

Will update this issue when the change has been deployed.

**Comment by manton** [comment]
This fix has been rolled out. @snarfed, lemme know if you notice any problems!

**Comment by snarfed** [comment]
Thanks for looking at this @manton! I'm still seeing micro.blog return HTML for the original example above though. Maybe the redirects are unhappy somehow?

```
$ curl -vL -H 'Accept: application/activity+json; q=0.9, application/ld+json;profile="https://www.w3.org/ns/activitystreams"; q=0.8, text/html; charset=utf-8; q=0.7' https://juhaliikala.com/activitypub/juha
* Trying 104.200.22.214:443...
* Connected to juhaliikala.com (104.200.22.214) port 443 (#0)
...
> GET /activitypub/juha HTTP/2
> Host: juhaliikala.com
> user-agent: curl/7.88.1
> accept: application/activity+json; q=0.9, application/ld+json;profile="https://www.w3.org/ns/activitystreams"; q=0.8, text/html; charset=utf-8; q=0.7
> 
< HTTP/2 302 
< access-control-allow-origin: *
< content-type: text/html;charset=utf-8
< date: Thu, 29 Jun 2023 14:48:34 GMT
< location: https://micro.blog/activitypub/juha?domain=juhaliikala.com
< server: Caddy
< server: nginx/1.14.2
< content-length: 0
< 
* Issue another request to this URL: 'https://micro.blog/activitypub/juha?domain=juhaliikala.com'
*   Trying [2600:3c00:1::68c8:16d7]:443...
* Connected to micro.blog (2600:3c00:1::68c8:16d7) port 443 (#1)
...
> GET /activitypub/juha?domain=juhaliikala.com HTTP/1.1
> Host: micro.blog
> User-Agent: curl/7.88.1
> Accept: application/activity+json; q=0.9, application/ld+json;profile="https://www.w3.org/ns/activitystreams"; q=0.8, text/html; charset=utf-8; q=0.7
> 
< HTTP/1.1 302 Found
< server: nginx/1.14.2
< date: Thu, 29 Jun 2023 14:48:34 GMT
< content-type: text/html;charset=utf-8
< content-length: 0
< location: https://micro.blog/juha?remote_follow=1
< connection: close
< 
* Issue another request to this URL: 'https://micro.blog/juha?remote_follow=1'
* Hostname micro.blog was found in DNS cache
*   Trying [2600:3c00:1::68c8:16d7]:443...
* Connected to micro.blog (2600:3c00:1::68c8:16d7) port 443 (#2)
...
> GET /juha?remote_follow=1 HTTP/1.1
> Host: micro.blog
> User-Agent: curl/7.88.1
> Accept: application/activity+json; q=0.9, application/ld+json;profile="https://www.w3.org/ns/activitystreams"; q=0.8, text/html; charset=utf-8; q=0.7
> 
< HTTP/1.1 200 OK
< server: nginx/1.14.2
< date: Thu, 29 Jun 2023 14:48:35 GMT
< content-type: text/html;charset=utf-8
< content-length: 7984
< connection: close
< 
<!DOCTYPE html>
<html class="theme-auto">
<head>
...
```

**Comment by manton** [comment]
@snarfed Sorry, I actually did _not_ get the change live everywhere. Fixed. Try again? Your `curl` above works for me now.

**Comment by snarfed** [comment]
confirmed, looks great now!
