### ISSUE TITLE
New post button no longer showing in Micro.blog for macOS v2.9.1

### ISSUE THREAD

**Issue by paulrobertlloyd** [microdotblog/issues#247]
The pen icon that previously appeared on the top right of the main window no longer appears:

<img width="873" alt="Screenshot 2023-06-30 at 22 35 04" src="https://github.com/microdotblog/issues/assets/813383/3820c4f7-d99c-4e71-b96f-f302ca73f7e5">

It is still possible to show this window by going to ‘File > New Post’.

**Comment by vincentritter** [comment]
Can confirm this bug @manton – it's when the window is small or default it will drop the new post icon in the top right.

When you resize it (make it larger), it comes back.

**Comment by paulrobertlloyd** [comment]
This was fixed in a recent release.
