### ISSUE TITLE
iOS app crashes when opening "Posts"

### ISSUE THREAD

**Issue by edoardob90** [microdotblog/issues#248]
On the latest iOS (17.3), Micro.blog app crashes every time the "Posts" section is being opened. The app is the latest version (3.2.1).

Even after trying the obvious steps (log out/in, uninstall/reinstall), nothing changes: the "Posts" section is unreachable.

Is there a way to extract some log files?

**Comment by manton** [comment]
This was fixed in a recent App Store release. Thanks!
