### ISSUE TITLE
Change of username doesn't update blog url and feed url

### ISSUE THREAD

**Issue by will-stone** [microdotblog/issues#25]
Changed my username from @stone to @ws, however my blog url hasn't updated:

![image](https://cloud.githubusercontent.com/assets/654103/25562913/3a44341c-2d89-11e7-99ac-28bb6ce84113.png)

**Comment by manton** [comment]
@will-stone Even if this isn't automatic, I agree that it should be at least possible to rename the hostname, which I currently have to do manually for people. If you haven't emailed help@micro.blog already, send a quick email there and I'll rename it for you. Thanks!

**Comment by issimonwoods** [comment]
+1 for auto-renaming on edit of a username.

**Comment by will-stone** [comment]
Looks like this is fixed...?
