### ISSUE TITLE
"activitypub" edits inadvertently made to bloggers urls

### ISSUE THREAD

**Issue by toddgrotenhuis** [microdotblog/issues#252]
multiple folks (myself included) have had our blog url on our microblog profile get inadvertently changed to the acvitypub follow URL, such as:

<img width="590" alt="image" src="https://github.com/microdotblog/issues/assets/165077/4a299de1-160a-46a5-bbdc-9ee53fab8191">

**Comment by manton** [comment]
This should be fixed now.
