### ISSUE TITLE
Datetime issue with incoming webmentions

### ISSUE THREAD

**Issue by gRegorLove** [microdotblog/issues#254]
I posted a [reply ](https://gregorlove.com/2024/02/i-went-for-a-day/)to a [micro.blog post](https://blog.grotenhuis.info/2024/02/15/how-did-i.html) and sent a webmention successfully. I think the timezone in my published date is getting dropped in m.b. though. It's `2024-02-15 17:15-0800` on my post, but in the [m.b. webmentions](https://micro.blog/webmention?target=https://micro.blog/toddgrotenhuis/31082019) it shows `2024-02-15T17:15:00+00:00`

I know my published date lacks the `T` separator, but I believe that's a valid ISO8601 format. I think I chose that in part because the mf2 date-time parsing normalizes to not use the T.

**Comment by manton** [comment]
Sorry it took so long for me to fix this. The date format parsing was fine, but the time zone was getting dropped anyway. I've fixed this for an update that will roll out this week. I've also corrected that mention. Thanks!
