### ISSUE TITLE
macOS app: Not easy to view own profile

### ISSUE THREAD

**Issue by paulrobertlloyd** [microdotblog/issues#259]
Sometimes it’s useful to view your own profile to check that something has been posted, or what currently appears in your profile ‘About me’ text. However, it’s not easy to access your own timeline from the macOS app.

The account indicator in the toolbar might be a good candidate for enabling this, but with multiple accounts this becomes an account switcher, so adding the ability to view your profile from this item might get tricky – maybe with a segmented control?

There’s an menu item ‘View → Go to user…’, and you can type in your own name, but that’s a few extra clicks.

Maybe the simplest option would be to add a menu item ‘View → Profile’ or similar?

**Comment by manton** [comment]
I'm adding more keyboard shortcuts for the next version. What about "Go to @username" with command-option-U, next to "Go to user"?

**Comment by paulrobertlloyd** [comment]
Not sure of the right Mac terminology, but would this mean that the ‘Go to user… ⌘U’ menu item would change to ‘Go to @​paulrobertlloyd ⌥⌘U’ when pressing the option key?

**Comment by manton** [comment]
I would make it two separate menu items so it's a little more discoverable. But yes, essentially it would look like:

<img width="257" alt="image" src="https://github.com/microdotblog/issues/assets/12312/63ae6eaa-6044-44ba-9bdb-bc3214a1028a">

Also changed my mind and made it shift instead of option, which is easier for people.

**Comment by paulrobertlloyd** [comment]
Yes, separate menu items makes sense. Love it!

**Comment by paulrobertlloyd** [comment]
Fixed in v3.2 🎉. Thanks @manton
