### ISSUE TITLE
Provide feedback to user about publish status (posting/posted/failed).

### ISSUE THREAD

**Issue by paulrobertlloyd** [microdotblog/issues#27]
Currently (in the iOS app at least), when publishing a post, there is no feedback, either to show the progress status of a post being published, or to indicate that a post has been successfully published (or not).

I understand that given the distributed nature of the platform, publishing may not be instantaneous; that’s fine, just please provide some indication that some work is happening behind the scenes. When a post is published, show it in the timeline, and/or provide messaging to confirm a successful post action.

**Comment by manton** [comment]
The feedback is much better in the last couple updates to the iOS app, showing a status bar and error message if there are problems. Thanks!
