### ISSUE TITLE
User avatar on home screen of iOS app not updating

### ISSUE THREAD

**Issue by paulrobertlloyd** [microdotblog/issues#29]
I updated my (Gravtar-linked) avatar soon after setting up my account, and while the new image appears next to my timeline posts, the blue default stubbornly remained on the home screen. In order to have it refresh, I ended up deleting the app (to force delete all associated documents and data), reinstalling it, and then signing in again.

TL;DR: caching on the avatar shown on the home screen should be refreshed more frequently!

**Comment by manton** [comment]
Thanks for the feedback! This is fixed in the latest version of the iOS app.
