### ISSUE TITLE
Position of ‘Sign Out’ button too close to home hardware button

### ISSUE THREAD

**Issue by paulrobertlloyd** [microdotblog/issues#30]
I accidentally signed out of micro.blog because I brushed against the ‘Sign Out’ button when reaching for the iPhone’s home button. Perhaps this button should be placed somewhere further away (perhaps the top of that list?)

**Comment by manton** [comment]
Thanks for the feedback. Someone else suggested a confirmation alert when signing out as well, which would help.

**Comment by manton** [comment]
We added a confirmation alert recently so it's not so easy to accidentally sign out. I think we'll adjust that menu in the future as it contains more items, but not for the next release.
