### ISSUE TITLE
Feature request: Being able to see more than the latest posts

### ISSUE THREAD

**Issue by jemostrom** [microdotblog/issues#33]
It looks like it's not possible to see more than just the latest posts. I would like to be able to see more (especially being able to delete my own test posts).

**Comment by orionp** [comment]
While this doesn't help with scrollback, you _can_ already delete your test posts.

Account > Edit Domains & Designs > Posts

Hope that helps!

**Comment by jemostrom** [comment]
Ahhh, that was NOT obvious :)

**Comment by orionp** [comment]
Nope! I only found it because I was walking the entire interface, poking at everything. Professional hazard, I'm afraid. Enjoy deleting!

**Comment by manton** [comment]
Closing this one too since you can now scroll further back. Thanks!
