### ISSUE TITLE
User timeline RSS feeds should have "From @author" as a title for each post

### ISSUE THREAD

**Issue by klundberg** [microdotblog/issues#34]
If I go to read the timeline/friend feed (micro.blog/feeds/username.xml) in my RSS reader, I can't see who a post is by in my reader unless I mouse over the link to the post. It would be much nicer to be able to read these via an RSS reader if each item could have a title that was something like `@author:` or `From @author` or `New post by @author` or something like that, concise but conveys who wrote the post in the text. See the screenshot below to see how it looks today when I add my timeline feed to feedbin.

![Example Screenshot](https://cloud.githubusercontent.com/assets/867898/25647698/574e0b2c-2f92-11e7-9701-f6e114997cab.png)

**Comment by Cj-Malone** [comment]
Instead of the author being put in the title it should just go into the `author` element ( http://www.rssboard.org/rss-specification#ltauthorgtSubelementOfLtitemgt ), `source` ( http://www.rssboard.org/rss-specification#ltauthorgtSubelementOfLtitemgt ) should probably be used as well.

**Comment by klundberg** [comment]
I don't disagree on principle. Some RSS readers may not show author prominently, though. If the author element was used, in the screenshot I provided it would show the author in gray text appended to the end of the date. Perhaps it could be added there and as part of a title string too?

**Comment by manton** [comment]
I think we can start by just making sure the `author` element is there and then test with more RSS readers to see how they look. I'm afraid you're right that many RSS readers probably don't expect there to be different authors for each item, and so it might not be as prominent as it should be for a timeline. But it's a good place to start and then revisit the issue.

**Comment by manton** [comment]
I've deployed a couple fixes to feeds, including adding the `author` element for RSS feeds. Going to close this for now but feel free to re-open if more improvements are needed.

**Comment by Cj-Malone** [comment]
@manton Any particular reason to not using the [source](http://www.rssboard.org/rss-specification#ltsourcegtSubelementOfLtitemgt) element as well?
