### ISSUE TITLE
Error when attempting to post from hosted account via micropub with Quill

### ISSUE THREAD

**Issue by chrisaldrich** [microdotblog/issues#38]
On my hosted microblog (http://micro.boffosocko.com remapped from http://c.micro.blog/) I can login into [Quill](https://quill.p3k.io/) via IndieAuth, but when I attempt to actually post a note I get the following error:

`Your endpoint did not return a Location header.
See [Creating a Micropub Endpoint](https://quill.p3k.io/creating-a-micropub-endpoint) for more information.`

along with the following:

HTTP/1.1 400 Bad Request
Server: nginx/1.6.2
Date: Wed, 03 May 2017 16:50:09 GMT
Content-Type: text/html;charset=utf-8
Content-Length: 15
Connection: keep-alive
Status: 400 Bad Request
X-XSS-Protection: 1; mode=block
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN

Invalid request 

I've heard others have had success, though I suspect they're with self-hosted versions.

Incidentally aaronpk indicated that the Quill server was seeing a 500 server error from micro.blog in the Quill logs for this.

**Comment by manton** [comment]
This is probably because currently the site URL in your user profile (stream.boffosocko.com) has to be verified _and_ match the site used for Micropub (micro.boffosocko.com). I'll work on adding a better error message for this. That limit can probably be removed, but I was concerned about the security and wanted to lock it down to a verified site to start with.

**Comment by chrisaldrich** [comment]
<a href="https://github.com/microdotblog/issues/issues/38" class="u-in-reply-to"></a>I tried the change of URL and attempted to post again with quill.
It made it a bit further and returned the following URL
http://c.micro.blog/2017/05/18/test-from-quill.html
but it was a 404 nginx page with no content and the post didn't go through...

**Comment by manton** [comment]
We've improved a bunch of things related to IndieAuth and Micropub, so I think we can close this out now. Thanks!
