### ISSUE TITLE
Delete should require confirmation

### ISSUE THREAD

**Issue by jthingelstad** [microdotblog/issues#39]
I just tapped wrong on the iOS app and deleted one of my entries faster than you can imagine. There is no undo and there is no confirmation dialog. The delete action badly needs a confirmation dialog to avoid accidental deletion.

**Comment by will-stone** [comment]
I'd vote for "undo"; that's the nicer UX.

**Comment by manton** [comment]
Undo would be great, but I did add a confirmation alert in the latest version, 1.3.3. Going to close this for now. Thanks!
