### ISSUE TITLE
Web: spaces at the end of text isn't visible

### ISSUE THREAD

**Issue by jemostrom** [microdotblog/issues#40]
If I want to write "Hello world" and have typed "Hello " then it's displayed as "Hello" in the text field- the insertion point being directly after 'o' - I can see no difference from when I have written "Hello". 

When I write 'w' then both ' ' and 'w' becomes visible and the insertion point is placed after the 'w'.

Not very important but I found it slightly annoying.

**Comment by issimonwoods** [comment]
This works for me now (iPad -> Safari).
