### ISSUE TITLE
Dozens of empty git commits

### ISSUE THREAD

**Issue by jthingelstad** [microdotblog/issues#42]
I’m mirroring my micro.blog to Github and the commits are very odd. When I add a new post there are dozens of commits, all blank. You can see what I’m referring to on [my repo commits](https://github.com/thingles/micro.thingelstad.com/commits/master). Most of these commits have no changes, [like this one](https://github.com/thingles/micro.thingelstad.com/commit/f83681a2f645e95f7d6a3d46e3aa54c8e79a6adb).

This isn't causing any problems that I can see, but it makes the commit log pretty useless to see changes over time. 

I didn’t even think it was possible to do an empty commit, but it looks like there is a `--allow-empty` option that does it.

**Comment by splorp** [comment]
I made mention of the empty git commits in issue #22 as well.

**Comment by manton** [comment]
Thanks. I think this must be for files that haven't actually changed, but they're being committed anyway. (It doesn't commit directly but instead uses the GitHub API via Octokit.)

Sorry about the clutter. I'm experimenting with a work-around.

**Comment by jthingelstad** [comment]
Worth noting that these empty commits can be removed once the source of them is fixed. `git filter-branch --prune-empty` will remove them from history which would be very nice to do.

**Comment by jthingelstad** [comment]
Should this issue be closed and track on #22 or do you want to close that one and track here. The CSS issue referenced in #22 sounds like it's fixed.

**Comment by jthingelstad** [comment]
As an FYI, I did a `git clone` of my mirrored micro.blog to my laptop and then did a `git filter-branch --prune-empty` and it churned through the repo and removed empty commits as expected:

```
Rewrite 66dda6f505860732731ff1e9c64dbea6d4392e8a (322/334) (13 seconds passed, remaining 0 predicted)    
Ref 'refs/heads/master' was rewritten
```

You have to force a push with `git push --force` after this due to the changes. It took my 332 commits to 92. So, for sure the empty commits can easily be removed.

I had some concerns this could move HEAD on master in weird ways but figured since micro.blog is using the API this probably wouldn't mattered. I did [publish another post](http://micro.thingelstad.com/2017/05/05/trying-git-filterbranch.html) and it successfully put the changes in Github so this seems to work just fine to clean up the repo.

**Comment by jthingelstad** [comment]
Since I recently [imported my Twitter archive](http://micro.thingelstad.com/2017/05/06/importing-tweets-from.html) into micro.blog I was curious to see what impact that had on this issue. It took a long time for the import to stabilize, and it still isn't all the way mirrored (about half of the posts have been mirrored now). But, I showed a commit count of **17,509**. I did a `filter-branch --proune-empty` and now have **3,059** commits. **14,450** of the commits were empty. 

It took approximately 12 minutes for the filter-branch to run.

**Comment by manton** [comment]
Thanks, this really needs to be improved. I noticed yesterday it was being rate-limited by GitHub too.

**Comment by manton** [comment]
This should be fixed now. Please let me know if you still see any problems with commits.

**Comment by jthingelstad** [comment]
@manton I don't think this issue is fixed. I’m seeing many, many empty commits as recent as 2 hours ago. 

https://github.com/thingles/micro.thingelstad.com/commits/master

https://github.com/thingles/micro.thingelstad.com/commit/5a5834f6cbfef768762d44bf0f7887a14f049b56

**Comment by splorp** [comment]
@manton Just confirming what @thingles stated in the previous comment.

While there are no longer “dozens” of empty commits (thank you!) … there are still a handful trickling into the repo. Here are the empty commits from my last update:

https://github.com/splorp/splorp.github.io/commit/c3e7a95a0a30c857ef1fe1209574d4914d4e1877
https://github.com/splorp/splorp.github.io/commit/40090ba0315f020ad8201c9c50704df97f094143
https://github.com/splorp/splorp.github.io/commit/5d77c87d04007fa95696d6110fe6887811c3257f
https://github.com/splorp/splorp.github.io/commit/9e593ea18e7ee99dfb304b59e376aa8e5dae931a
https://github.com/splorp/splorp.github.io/commit/7e64f5e3b55eac055430f3be4c1da11c10321f0d
https://github.com/splorp/splorp.github.io/commit/6fee52551765d721473eabe9dfdbd4a1a24a4167
https://github.com/splorp/splorp.github.io/commit/d402b06c82b6c9fc8245219d1955368e4f7ded03
https://github.com/splorp/splorp.github.io/commit/9b937cf64d98ab703ed9a6fd57d0d0a4c2fec989

**Comment by jthingelstad** [comment]
Another data point. I had 17,686 commits on my repo at https://github.com/thingles/micro.thingelstad.com. I ran `git filter-branch --prune-empty -f` and was left with 10,815 commits. 6,871 empty commits. Note that 28 days ago my comment above I had 3,059 after a prune, so of the 14,627 commits since then about 47% of them were empty.

**Comment by jthingelstad** [comment]
I wonder if this issue should be reopened? Or perhaps it doesn't really matter that much.

I did another `git filter-branch --prune-empty -f` on my cloned microblog repo. It took about 30 minutes and started with 62,943 commits and finished with 28,406 commits that were not empty.

**Comment by splorp** [comment]
I would vote for reopening this issue.
