### ISSUE TITLE
Use letsencrypt to generate valid key for custom domains

### ISSUE THREAD

**Issue by dougbeal** [microdotblog/issues#45]
Right now you get a certificate error for ssl access with a custom domain (https://micro.dougbeal.com).  It would be great if a certificate was generated that matched the custom domain.

**Comment by dougbeal** [comment]
Dupe of #35

**Comment by manton** [comment]
We allow SSL for custom domains now, and I've enabled it for micro.dougbeal.com. Thanks @dougbeal!
