### ISSUE TITLE
micro.blog/user and RSS feed / sidebar.js slow to update

### ISSUE THREAD

**Issue by will-stone** [microdotblog/issues#46]
I understand there will be some lag in the early days of the service but weirdly my ws.micro.blog updates a good 5 minutes before micro.blog/ws and my sidebar.js feed.

**Comment by manton** [comment]
Thanks. I just made some additional fixes this morning to speed things up. We can leave this open as there's still room for improvement, but should be much faster now.

**Comment by will-stone** [comment]
I presume speed has increased since May last year. Closing.
