### ISSUE TITLE
Post Truncated in micro.blog feed vs individual post page

### ISSUE THREAD

**Issue by dougbeal** [microdotblog/issues#48]
I noticed a post that didn't make much sense.  <img width="646" alt="truncated" src="https://cloud.githubusercontent.com/assets/41865/25918725/47132dd8-3581-11e7-899b-0fc088c2d6f4.png">
ends at:

>  to get him to...

wc reports      1      56     283

  When viewing the [post's individual page]( http://knsontag.micro.blog/2017/05/10/took-the-noodleboy.html), it looked fine.

> I scheming to get him to feed the dog & scoop the cat box…

wc reports       1      64     316

**Comment by manton** [comment]
Thanks. There's an edge case here where some long posts don't include a link back to the full post except in the date/time link. I'm fixing this today.

**Comment by manton** [comment]
I think this was fixed a while back. Closing.
