### ISSUE TITLE
Allow micro.blog hosted sites to add Google Analytics

### ISSUE THREAD

**Issue by jthingelstad** [microdotblog/issues#49]
It would be nice if you could add a Google Analytics code to your micro.blog hosted site.

**Comment by kaapow** [comment]
I'd rather have some super simple analytics backed into Micro.blog itself. So effectively we get number of unique visitors maybe which country they're from and the top 10 most popular posts over certain periods of time.

**Comment by jthingelstad** [comment]
I’m going to retract my request on this. I've done more thinking about this and I [no longer use Google Analytics](https://www.thingelstad.com/2017/removed-google-analytics/). I could see supporting this with a setting, but would default it to off.

**Comment by manton** [comment]
We're still considering whether there should be built-in analytics and what they look like, but in the meantime you can now add custom JavaScript under Account → Posts → Edit Domain & Design → Footer. It should be possible to use Google Analytics or another service this way. (Of course, this will count page views in a web browser but not views in the Micro.blog timeline.)

Thanks!
