### ISSUE TITLE
Micro.blog hosted sites feed.json missing required version field

### ISSUE THREAD

**Issue by jthingelstad** [microdotblog/issues#51]
My micro.blog hosted site's [feed.json](http://micro.thingelstad.com/feed.json) is missing the required `version` field per [the spec](https://jsonfeed.org/version/1).

**Comment by manton** [comment]
Thanks, I meant to fix that today. These feeds predate the announcement, so I didn't want to confuse everyone by including the `version` too early. :-) Will be fixed soon.

**Comment by jthingelstad** [comment]
I see this now…

```
curl --silent 'http://micro.thingelstad.com/feed.json' | grep version
	"version": "https://jsonfeed.org/version/1",
```

Looks like this should be closed now. Closing.
