### ISSUE TITLE
More structure for _posts directory needed

### ISSUE THREAD

**Issue by jthingelstad** [microdotblog/issues#52]
Right now micro.blog is putting all posts directly into the `_posts` directory. With a large amount of content this become hard to manage or navigate. It would be nice for users that end up looking at the source markdown files to at least put these in year and month folders, maybe even days as well.

For an example see https://github.com/thingles/micro.thingelstad.com/tree/master/_posts.

**Comment by manton** [comment]
You're right, this is going to get unwieldy very soon, especially when importing Twitter posts. Thanks.

**Comment by ghost** [comment]
Was this implemented?

**Comment by manton** [comment]
No, and because we disabled the GitHub mirroring feature, I think it's best to just close this issue since it no longer applies. The backup archive we export now does structure the posts by date to avoid this problem, and any future feature similar to the GitHub mirroring will be based on that.
