### ISSUE TITLE
Links and Maximum Tweet Lengths when Cross-posting to Twitter

### ISSUE THREAD

**Issue by jbrayton** [microdotblog/issues#55]
This is a post I made to micro.blog:
https://johnbrayton.micro.blog/2017/06/03/trump-administration-rolls.html

This is the resulting cross-post on Twitter:
https://twitter.com/johnbrayton/status/870804400968564736

Since the post consists of a link and 72 characters of text, I expected the tweet to contain all of the text and the link. Instead the tweet was truncated and linked to the micro.blog post. I assume the reason is that the cross-posting logic does not take into account that Twitter counts all URLs as being 20 characters long when determining whether a tweet is no longer than 140 characters.

**Comment by pcmhatre** [comment]
Maybe this can be addressed by auto-truncating with a micro URL before it send it to Twitter?

**Comment by manton** [comment]
Pretty sure this was fixed long ago now. Thanks!
