### ISSUE TITLE
Line Feeds in Posts

### ISSUE THREAD

**Issue by jbrayton** [microdotblog/issues#56]
When composing this post I used line feed characters with the expectation that each bulleted list item would start on a new line.

https://johnbrayton.micro.blog/2017/06/05/wwdc-hopes-faster.html

If I look at the source for the page I can see that the line feed characters are there, but that the formatting is lost in HTML. I ask that either new line and carriage return character sequences be converted to <br> elements or that the CSS hard wrap on line feed / carriage return sequences.

I think I recall seeing similar behavior by the iOS app when displaying that post, but the post has gotten old so I no longer see it in the app.

**Comment by manton** [comment]
Right now Micro.blog is still fairly strict Markdown, which means if you want a new line you need to add a space at the end of each line. (Or add two returns to make a new paragraph.) I've been considering recently deviating a little from Markdown on this, but haven't made any changes yet.

Also the best way to do a bullet list is to start each line with an asterisk, and those will be converted to a proper HTML list. Going to close this for now. Thanks.
