### ISSUE TITLE
SVG Icon to link to syndicated micro.blog posts

### ISSUE THREAD

**Issue by dg01d** [microdotblog/issues#61]
It would be great to have some sort of icon to use on my own site to show that a post has been syndicated to micro.blog. The app-iconography of the star-in-bubble would be a candidate for this, albeit manton would probably prefer to retain this as the app-icon.

**Comment by manton** [comment]
Thanks for the suggestion! Maybe we could produce an even simpler version of the icon that would be good for this. Or something like the current favicon could be used currently.

**Comment by paulrobertlloyd** [comment]
I added [an SVG icon for Micro.blog](https://simpleicons.org/?q=microblog) to the Simple Icons collection a few weeks ago. Perhaps this is useful to you @dg01d?

**Comment by manton** [comment]
There's also [an official SVG icon](http://help.micro.blog/2018/resources/) now as well. Thanks!
