### ISSUE TITLE
Long posts with unicode characters not truncated correctly

### ISSUE THREAD

**Issue by manton** [microdotblog/issues#62]
Example from a user, pasting a bunch of country flags (which are 4-byte characters) that go over the 280-character limit usually produces bad truncation:

🇺🇸🇦🇽🇦🇱🇩🇿🇦🇸🇦🇩🇦🇴🇦🇬🇦🇷🇦🇼🇦🇺🇦🇹🇧🇸🇧🇭🇧🇩🇧🇧🇧🇾🇧🇪🇧🇿🇧🇯🇧🇲🇧🇹🇧🇴🇧🇦🇧🇼🇧🇷🇧🇳🇧🇬🇧🇫🇧🇮🇰🇭🇨🇲🇨🇦🇨🇻🇰🇾🇨🇱🇨🇳🇨🇴🇨🇬🇨🇩🇨🇷🇨🇮🇭🇷🇨🇾🇨🇿🇩🇰🇩🇲🇩🇴🇪🇨🇪🇬🇸🇻🇪🇪🇪🇹🇫🇴🇫🇯🇫🇮🇫🇷🇬🇫🇬🇦🇬🇲🇬🇪🇩🇪🇬🇭🇬🇮🇬🇧🇬🇷🇬🇱🇬🇵🇬🇺🇬🇹🇬🇬🇬🇾🇭🇹🇭🇳🇭🇺🇮🇸🇮🇳🇮🇩🇮🇪🇮🇱🇮🇹🇯🇲🇯🇵🇯🇪🇯🇴🇰🇿🇰🇪🇰🇷🇰🇼🇱🇦🇱🇻🇱🇧🇱🇮🇱🇹🇱🇺🇲🇰🇲🇬

**Comment by manton** [comment]
Doesn't work so well in GitHub either, looks like.

**Comment by issimonwoods** [comment]
I tested this in iOS and it looks like it worked.

- [on my blog](https://simonwoods.online/2021/06/25/231811.html)
- [on my profile](https://micro.blog/simonwoods)

**Comment by manton** [comment]
Great, thanks!
