### ISSUE TITLE
Micro.blog to Known via micropub

### ISSUE THREAD

**Issue by chrisaldrich** [microdotblog/issues#63]
Just in case it's not officially in the queue yet, I saw this note the other day:

> I'm still a little hazy on the plumbing details of all the bits and pieces of IndieWeb but I would have thought that if withKnown has a micropub endpoint and micro.blog can send to the WordPress endpoint, it ought to be able to send to WithKnown. But I'm probably exposing my ignorance. And maybe it is on the roadmap.

via http://stream.jeremycherfas.net/2017/im-still-a-little-hazy-on-the-plumbing-details-of

**Comment by manton** [comment]
Thanks, I replied here too: https://micro.blog/cn/172274

It really should work already.

**Comment by tantek** [comment]
If this is already doable - are there step by step docs for how to setup your micro.blog client(s) (e.g. the micro.blog iOS client) and/or account to post to your Known website that could be linked here?

**Comment by cdn** [comment]
@tantek this morning I linked iOS micro.blog to charlienovemb.re by pressing the top–right new post button 💬  in the app.
This offered a text box to put a URL into.
There was then a handshake with Known (I was already logged in).

Subsequent presses of new post offer a text box to write in…

**Comment by jeremycherfas** [comment]
Should the link be to the home page? I tried that, and got to the
Authorize page. Duly authorised, returned to the OSX app, posted and
got an error.

On Tue, 24 Oct 2017, at 10:27 AM, cdn wrote:
> @tantek[1] this morning I linked iOS micro.blog to charlienovemb.re by
> pressing the top–right new post button 💬  in the app.>  This offered a text box to put a URL into.
>  There was then a handshake with Known (I was already logged in).


> Subsequent presses of new post offer a text box to write in…


> — You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub[2], or mute the
> thread[3].> 


Links:

  1. https://github.com/tantek
  2. https://github.com/microdotblog/issues/issues/63#issuecomment-338914103

**Comment by manton** [comment]
This was fixed recently and Micro.blog posting now works with Known again. Thanks everyone! Closing.
