### ISSUE TITLE
Carriage returns in Twitter cross-posting add an extra space

### ISSUE THREAD

**Issue by benjohnson** [microdotblog/issues#65]
This markup:

```
We’ve had an Echo for three days and my two-year-old already talks to her like she’s part of the family:

Me: "Time to go to bed. Alexa, turn off the lights."
Toddler: "No! Alexa, stop please!"

There's probably a lesson somewhere in here about the future of interfaces.
```

Translated into this Tweet:
![image](https://user-images.githubusercontent.com/69549/33913794-4e02aaf0-df69-11e7-8d7a-8ccea6af29f5.png)

Note the extra space before the M and the T after the carriage returns. I'm not sure yet if this is part of the cross-posting logic or if it's an issue with the app, but the markup seems to present correctly in micro.blog.

**Comment by manton** [comment]
I think we've got this fixed now. Thanks!
