### ISSUE TITLE
Cut-off screens in iOS app with iPhone 5S/iOS 10.3.3

### ISSUE THREAD

**Issue by sardisson** [microdotblog/issues#67]
I'm not sure if this is an iPhone 5S issue, or an iOS 10.3.x issue, or a combo of both, or just me,  but the Settings screen and the External Blog screen are cut off at the top.  I don't know if I'm missing any settings or if it's "just" cosmetic….  Every other screen seems correct as far as I can tell.

![img_4468](https://user-images.githubusercontent.com/13267005/34474604-0effe958-ef4f-11e7-8e2f-de2e12e0f875.PNG)
![img_4469](https://user-images.githubusercontent.com/13267005/34474605-0f0cf1ca-ef4f-11e7-9d63-d4498c158cbb.PNG)

**Comment by manton** [comment]
Thanks for reporting this. It's not happening for me right now, but I have seen it too in some situations… I'll try to reproduce and get it fixed soon.

**Comment by paulrobertlloyd** [comment]
Wonder if this is still an issue in Micro.blog 2.0?

**Comment by issimonwoods** [comment]
Haven’t tested on the 5S/original SE size but these screens are fine on my SE 2.

**Comment by manton** [comment]
Thanks, this should be good now. Closing.
