### ISSUE TITLE
Link to original post

### ISSUE THREAD

**Issue by gerwitz** [microdotblog/issues#72]
Even if a post fits into Micro.blog and needs no "see also", a subtle "posted from" link would be nice for finding the original feed source.

**Comment by gerwitz** [comment]
Even more important, can we get a [rel=canonical](http://microformats.org/wiki/rel-canonical) on the post's "conversation" URL, linking to the original?

**Comment by ghost** [comment]
I assume this is for posts that come from an external site, rather than a Micro.blog hosted site?

**Comment by gerwitz** [comment]
Exactly, and fits nicely with #83 and #79 to let external “indie” sites participate in lower-case micro.blog as peers.

**Comment by ghost** [comment]
Thinking about it, the timestamp already links to the source. Although, that is perhaps _too_ subtle as compared to the examples you provide.

**Comment by gerwitz** [comment]
Ah, maybe this was changed since I opened this issue. I don’t feel strongly about the prominence of the link, but of course a rel=canonical would still be great.

**Comment by manton** [comment]
I've now added rel=canonical to the link on the Micro.blog page for that post (and conversation). Thanks!
