### ISSUE TITLE
Don't show IndieAuth authorization_endpoint if user hasn't registered for RelMeAuth

### ISSUE THREAD

**Issue by EdwardHinkle** [microdotblog/issues#80]
Currently a user can only use IndieAuth if they have set up RelMeAuth (Twitter/GitHub verification). My app supports both IndieAuth AND signing in via email. Currently I've just added a button choice for the user to select either "Sign in using Email" or "Sign in using IndieAuth". I don't want the user to have to make that choice.

What I would like to do is default to using IndieAuth if they have added either Twitter or GitHub urls (RelMeAuth) or email if they have not. There is no way currently for me to determine if they have IndieAuth/RelMeAuth set up or not so I have to present both options.

My recommendation is that the "authorization_endpoint" for IndieAuth gets added to the page if the user has entered either a GitHub or Twitter url since that is currently required to make IndieAuth work. Thus, if I query for an authorization_endpoint and find one, I can be rest assured IndieAuth should work fine as a log-in mechanism. If no endpoint is found, then I can send the user an email to log in.

**Comment by manton** [comment]
Worked around this issue by making Micro.blog a full IndieAuth provider. Everyone can use it so it can always be enabled now and guaranteed to work. Thanks!
