### ISSUE TITLE
Endpoint that returns either the micro.blog url or the micro.blog post id when given a canonical url

### ISSUE THREAD

**Issue by EdwardHinkle** [microdotblog/issues#81]
It would be extremely useful for an app to be able to take a given url and find out if that url is considered a post within the micro.blog system.

Essentially you would pass in the canonical URL and the endpoint with either return the post id for that article within micro.blog OR the full micro.blog URL of that url. If the url doesn't exist it could just return 404 or a similar HTTP error

**Comment by manton** [comment]
I've decided to update the conversation.js endpoint (in JSON Feed) to include the post URL in "home_page_url". You can grab this with a request like:

https://micro.blog/conversation.js?format=jsonfeed&url=https://your-site-here/your-post.html

There is also a hidden preference I can enable for anyone's feed that sends a Webmention to your site when Micro.blog processes the feed. That will usually require special handling so it doesn't just show up on your site like a comment.
