### ISSUE TITLE
iOS app: Unable to edit/refresh URL for ‘WordPress or compatible weblog‘

### ISSUE THREAD

**Issue by paulrobertlloyd** [microdotblog/issues#84]
Should I wish to change the external (non-micro.blog hosted) blog I post to, I am unable to achieve this using the iOS app. Once a URL has been configured and authenticated, the only option is to choose between publishing to a ‘Micro.blog hosted weblog’, or a ‘WordPress or compatible weblog’, with the second option having no ability to update its URL (During set-up, the URL is configured when you first attempt to post to the external weblog):

<img src="https://user-images.githubusercontent.com/813383/38163282-9314100e-34e9-11e8-8f8c-bb84c1f95461.png" width="320">

In my particular case, I don’t actually wish to change the URL; I’ve updated my Micropub endpoint and so need the app to discover and authentic with it, and not use the one discovered when I first set up posting via Micropub.

Note: this is not an issue in the macOS app, as the URL field is displayed when you select ‘WordPress or compatible weblog’:

![](https://user-images.githubusercontent.com/813383/38163264-3dd83e30-34e9-11e8-9d02-002985db7e60.png)

To resolve this issue, I had to delete the iOS app, reinstall and reconfigure.

It would seem that the resolution to this article would be to have the iOS app behave in a way that is consistent with the macOS app.

**Comment by issimonwoods** [comment]
Assuming this is has not changed: +1

**Comment by paulrobertlloyd** [comment]
Fixed in 3.0
