### ISSUE TITLE
macOS app: With multiple accounts, can no longer view own timeline

### ISSUE THREAD

**Issue by paulrobertlloyd** [microdotblog/issues#85]
Micro.blog for macOS. Once you have multiple accounts set up, clicking on the username portion in the left column reveals a menu for switching accounts. However, this means you can no longer click on this item to view your own timeline.

**Comment by issimonwoods** [comment]
There should probably be a specific “Profile” link of its own. I can understand the desire for elegance and reducing clutter but this seems to come much closer to the “junk drawer” philosophy.

Related: #66

**Comment by paulrobertlloyd** [comment]
Given the layout changes introduced in v2 of the app, I think this bug is no longer relevant so am closing.

**Comment by paulrobertlloyd** [comment]
Replaced by #259.
