### ISSUE TITLE
an explanation for the emojis that replace hashtags

### ISSUE THREAD

**Issue by mhellwig** [microdotblog/issues#87]
hashmojis? Something like that anyway.

If I go to https://micro.blog/discover there are usually at least two clickable emoji-like sigils shown at the top of the page.

Is there a list of them anywhere? How are they supposed to be used? Are they emojis? (in terms of entering them, I mean).

Do I even understand correctly that they are used as an analogue to hashtags?

**Comment by sardisson** [comment]
https://burk.io/discover contains a list of the operational "tagmoji topics" as well as a community suggestions list for future tagmoji,  and the emoji that Micro.blog looks for.

Manton blogged about it some here: https://www.manton.org/tag/tagmoji

**Comment by manton** [comment]
We've also started mirroring the community list over on the main help page: http://help.micro.blog/2018/tagmoji/. As new emoji are proposed and implemented we'll update the list. Thanks!
