### ISSUE TITLE
macOS app: Should new posts be shown on New Post screen?

### ISSUE THREAD

**Issue by paulrobertlloyd** [microdotblog/issues#88]
Small thing, but it seems weird for the number of new posts on the timeline to be shown on the ’New Post’ screen.

<img width="652" alt="screen shot 2018-04-23 at 17 01 21" src="https://user-images.githubusercontent.com/813383/39139211-321e38fa-4719-11e8-86cb-2676aebdaa84.png">

**Comment by ghost** [comment]
This _looks_ like a bug. Does it still happen?

**Comment by paulrobertlloyd** [comment]
@simon-woods Ooh, the app no longer does this, whoop! Closing issue.
