### ISSUE TITLE
Allow photo posting in original orientation. 

### ISSUE THREAD

**Issue by roobottom** [microdotblog/issues#9]
It would be great to be able to post a photo from iOS in its original orientation. I.e., not cropping it to a square. Thanks!

**Comment by manton** [comment]
Thanks for the feedback! I think in the future we might default to square but have a little icon that let's you toggle to the original aspect ration, similar to what Instagram does today.

**Comment by roobottom** [comment]
Why copy what Instagram does? Their use case is completely different. I'd expect that the default behavior is to post the original and add cropping as a feature later on.

**Comment by manton** [comment]
Fair point. But since we started with square, it's too late to go back and reverse the default... We'll continue to improve this and make it more flexible.

**Comment by roobottom** [comment]
Sorry to be an arse about this. My intended use-case was to post a photo a day and then cross-post to my own blog, so the cropping by default has thrown me. Thanks, Manton, you've built a brilliant service here!

**Comment by manton** [comment]
Thank you! Good to hear the feedback and the use-case. (And I love the idea of posting a photo every day.)

**Comment by paulrobertlloyd** [comment]
Also a little surprised that the a.) photos are automatically cropped to a square and that b.) in the future, even if you can opt-out of this, the default will remain a square. What aspect of the service will break should a photo not have a 1:1 ratio?

**Comment by manton** [comment]
@paulrobertlloyd Nothing will break if the photo isn't 1:1. That limitation is in the iPhone app and completely independent of the rest of the Micro.blog platform. (Some people are already posting photos from other blogs that have different aspect ratios.)

**Comment by manton** [comment]
This has been done for a while now. There's a toggle to keep the original aspect ratio.
