### ISSUE TITLE
Could 🔖 be removed from the books discovery emoji list?

### ISSUE THREAD

**Issue by kitt** [microdotblog/issues#90]
The 🔖 emoji is used by the community for tagging links, and currently (as of yesterday) is used to surface book-related posts on the discover/books stream.

Since not all links point to books (though, admittedly a lot of [Chris](https://micro.blog/c)' links **do** point to books), could this emoji be removed from the discover/books stream ?

If/when the `discover/weblinks` stream launches, the 🔖 emoji would work wonderfully there. @jasonburk already has it listed on his [discovery index](https://burk.io/discover).

**Comment by manton** [comment]
Thanks, I'm going to make this change. At first I thought people would use 🔖 for books too, but in practice it seems very rare.

**Comment by manton** [comment]
I've finally made this change to remove 🔖.
