### ISSUE TITLE
Followers/Following counts

### ISSUE THREAD

**Issue by yourhead** [microdotblog/issues#97]
I kind of like that micro.blog tries to consciously avoid the ego-stats of "likes" and "followers".  On the flip side, browsing through the follower/following lists of my friends is a good way to find people -- both people I already know and people that just have common interests.

My recommendation:  get rid of the counts.  Just have lists of followers/following users for browsing.

**Comment by cheesemaker** [comment]
What do you think about the implementation now that you can browse the users that you aren't following? It seems like a good hybrid of being able to discover new people without the ego-stats.

**Comment by yourhead** [comment]
honest opinion:  it still feels a bit anemic to me. but browsing users you don't yet follow is a good step.

unpopular opinion: all of the ego-stats had positive aspects as well as the obvious negatives. with them al removed i find it too easy to drift away from micro.blog.

i think there might have been a few babies in the ego-stat bathwater.

**Comment by issimonwoods** [comment]
In the couple of years since the last reply, I feel even better about the current implementation of these lists and would strongly dislike the addition of any more public information to profiles.

**Comment by manton** [comment]
I agree, let's keep the current behavior. One change I do want to make soon is to re-order the following list so that more active users are at the top (but slightly random to avoid everyone seeing the same people in the list).
